apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nextcloud.name" . }}-deployment
  labels:
    app.kubernetes.io/component: {{ .Values.controller.component }}
    {{- include "nextcloud.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.deployment.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- with .Values.deployment.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.controller.component }}
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  replicas: {{ .Values.deployment.replicaCount }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.deployment.component }}
        {{- range $key, $value := .Values.deployment.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
        - name: nextcloud
          image: "{{ .Values.image.nextcloud.registry }}/{{ .Values.image.nextcloud.repository }}:{{ default .Chart.AppVersion .Values.image.nextcloud.tag }}"
          imagePullPolicy: {{ .Values.image.nextcloud.pullPolicy }}
          args:
          {{- if gt .Values.deployment.replicaCount 1.0 }}
            - --leader-elect
          {{- end }}
          {{- with .Values.deployment.containers.nextcloud.extraArgs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.deployment.containers.nextcloud.extraEnvs }}
          env:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "nextcloud.name" . }}-env-config
          ports:
            - containerPort: {{ .Values.service.portMain.port }}
              protocol: TCP
              name: http
          {{- if and .Values.deployment.livenessProbe.enabled (not .Values.nginx.enabled) }}
          livenessProbe:
            httpGet:
              path: /status.php
              port:  {{ .Values.service.portMain.port }}
              httpHeaders:
              - name: Host
                value: {{ .Values.nextcloud.host | quote }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if and .Values.deployment.readinessProbe.enabled (not .Values.nginx.enabled) }}
          readinessProbe:
            httpGet:
              path: /status.php
              port:  {{ .Values.service.portMain.port }}
              httpHeaders:
              - name: Host
                value: {{ .Values.nextcloud.host | quote }}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if and .Values.deployment.startupProbe.enabled (not .Values.nginx.enabled) }}
          startupProbe:
            httpGet:
              path: /status.php
              port:  {{ .Values.nextcloud.containerPort }}
              httpHeaders:
              - name: Host
                value: {{ .Values.nextcloud.host | quote }}
            initialDelaySeconds: {{ .Values.deployment.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.deployment.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.deployment.startupProbe.failureThreshold }}
          {{- end }}
          securityContext:
          {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          resources:
          {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- with .Values.deployment.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if not .Values.persistence.data.enabled -}}
      volumeMounts:
        - name: nginx-config-vl
          mountPath: "/etc/nginx/nginx.conf"
          subPath: nginx.conf
          readOnly: true
        - name: {{ template "nextcloud.name" . }}-data-vl
          mountPath: "/var/www/html/data"
      {{- end -}}
    {{- if not .Values.persistence.data.enabled -}}
    volumes:
      - name: {{ template "nextcloud.name" . }}-data-vl
        claimName: {{ template "nextcloud.name" . }}-pvc-data
    {{- end -}}