apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nextcloud.name" . }}-deployment
  labels:
    app.kubernetes.io/component: {{ .Values.controller.component }}
    {{- include "nextcloud.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.deployment.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- with .Values.deployment.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.controller.component }}
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  replicas: {{ .Values.deployment.replicaCount }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.deployment.component }}
        {{- range $key, $value := .Values.deployment.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
        - name: nextcloud
          image: "{{ .Values.deployment.containers.nextcloud.registry }}/{{ .Values.deployment.containers.nextcloud.repository }}:{{ default .Chart.AppVersion .Values.deployment.containers.nextcloud.tag }}"
          imagePullPolicy: {{ .Values.deployment.containers.nextcloud.pullPolicy }}
          args:
          {{- if gt .Values.deployment.replicaCount 1.0 }}
            - --leader-elect
          {{- end }}
          {{- with .Values.deployment.containers.nextcloud.extraArgs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.deployment.containers.nextcloud.extraEnvs }}
          env:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "nextcloud.name" . }}-env-config
          ports:
            - containerPort: 9000
              name: fpm
            - containerPort: 8090
              name: metrics
            - containerPort: 8080
              name: healthz
          livenessProbe:
          {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          securityContext:
          {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          resources:
          {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- with .Values.deployment.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if not .Values.persistence.data.enabled -}}
      volumeMounts:
        - name: nginx-config-vl
          mountPath: "/etc/nginx/nginx.conf"
          subPath: nginx.conf
          readOnly: true
        - name: {{ template "nextcloud.name" . }}-data-vl
          mountPath: "/var/www/html/data"
      {{- end -}}
    {{- if not .Values.persistence.data.enabled -}}
    volumes:
      - name: {{ template "nextcloud.name" . }}-data-vl
        claimName: {{ template "nextcloud.name" . }}-pvc-data
    {{-end-}}