apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  WORDPRESS_DB_HOST: {{ .Values.config.database.host }}
  WORDPRESS_DB_USER: {{ .Values.config.database.user }}
  WORDPRESS_DB_PASSWORD: {{ .Values.config.database.password }}
  WORDPRESS_DB_NAME: {{ .Values.config.database.name }}
  WORDPRESS_TABLE_PREFIX: {{ .Values.config.database.tablePrefix }}
