name: Cleanup Deployment
concurrency: 
    group: no-group
    cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  cleanup-deployments:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  cleanup-releases:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          repo: <owner>/<repoName> # defaults to current repo
          keep_latest: 3
          keep_min_download_counts: 1
          delete_expired_data: 10
          delete_tag_pattern: beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
